services:
  gitlab:
    image: gitlab/gitlab-ce:18.2.2-ce.0
    container_name: gitlab
    restart: unless-stopped
    environment:
      GITLAB_HOME: /opt/gitlab
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.50:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 21
      GITLAB_SHELL_CREDENTIALS_PATH: /root/.gitlab_shell_credentials
    ports:
      - '8929:8929'
      - '443:443'
      - '21:21'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
